<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <AssemblyVersion>1.2.2.0</AssemblyVersion>
    <FileVersion>1.2.2.0</FileVersion>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Version>1.2.2.0</Version>
    <Authors>barimale</Authors>
    <Description>.NET QuestDB Change Tracker API - WAL-based change detection and tracking for QuestDB tables with event-driven architecture</Description>
    <RepositoryUrl>https://github.com/barimale/QuestDB.Change.Tracker</RepositoryUrl>
    <PackageTags>QuestDB,WAL,ChangeTracking,Events,Database</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.CommandLine" Version="6.13.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Npgsql">
      <Version>10.0.2</Version>
    </PackageReference>
  </ItemGroup>

</Project>
