<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <AssemblyVersion>3.0.3.17</AssemblyVersion>
    <FileVersion>3.0.3.17</FileVersion>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Version>3.0.3.17</Version>
    <Authors>barimale</Authors>
    <Description>.NET Consul Client provided with eager and lazy appSettings and connectionStrings adapters</Description>
    <RepositoryUrl>https://github.com/barimale/ConfigurationManager.Api</RepositoryUrl>
    <PackageTags>Consul</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Consul" Version="1.7.14.7" />
    <PackageReference Include="NodaTime" Version="3.3.2" />
    <PackageReference Include="NuGet.CommandLine" Version="6.13.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Npgsql">
      <Version>10.0.2</Version>
    </PackageReference>
  </ItemGroup>

</Project>
